language: node_js
node_js:
  - "0.12"

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: npm run travis

before_deploy:
  - "sed -i -E -e \"s/0\\.0\\.0/$TRAVIS_TAG/\" package.json"

deploy:
  provider: npm
  api_key: $NPM_API_KEY
  email: dev@medicmobile.org
  on:
    tags: true
